-- Sample Data for AMPLIFY

-- Note: User IDs should be generated by Supabase Auth
-- Replace these UUIDs with actual auth.users IDs after creating users

-- Sample users (insert after Supabase Auth user creation)
-- INSERT INTO public.users (id, email, full_name, role)
-- VALUES
--   ('UUID_FROM_AUTH', 'admin@institution.edu', 'Admin User', 'admin'),
--   ('UUID_FROM_AUTH', 'teacher@institution.edu', 'John Smith', 'teacher'),
--   ('UUID_FROM_AUTH', 'student1@institution.edu', 'Emma Davis', 'student'),
--   ('UUID_FROM_AUTH', 'student2@institution.edu', 'James Wilson', 'student'),
--   ('UUID_FROM_AUTH', 'student3@institution.edu', 'Sophia Martinez', 'student');

-- Sample classes (use actual teacher_id from auth)
INSERT INTO public.classes (name, subject, grade_level, section, teacher_id, color)
VALUES
  ('Mathematics - Grade 10A', 'Mathematics', 'Grade 10', 'A', 'TEACHER_UUID_HERE', 'blue'),
  ('Mathematics - Grade 10B', 'Mathematics', 'Grade 10', 'B', 'TEACHER_UUID_HERE', 'purple'),
  ('Advanced Math - Grade 11', 'Mathematics', 'Grade 11', 'A', 'TEACHER_UUID_HERE', 'green'),
  ('Calculus - Grade 12', 'Mathematics', 'Grade 12', 'A', 'TEACHER_UUID_HERE', 'orange');

-- Sample projects
INSERT INTO public.projects (class_id, name, description, due_date, progress, status)
SELECT 
  c.id,
  'Real-World Applications of Quadratic Functions',
  'Students will explore practical applications of quadratic equations in real-world scenarios',
  CURRENT_DATE + INTERVAL '3 days',
  75,
  'active'
FROM public.classes c WHERE c.name = 'Mathematics - Grade 10A'
LIMIT 1;

INSERT INTO public.projects (class_id, name, description, due_date, progress, status)
SELECT 
  c.id,
  'Mathematical Modeling Project',
  'Create mathematical models to solve real-world problems',
  CURRENT_DATE + INTERVAL '7 days',
  45,
  'active'
FROM public.classes c WHERE c.name = 'Mathematics - Grade 10B'
LIMIT 1;

INSERT INTO public.projects (class_id, name, description, due_date, progress, status)
SELECT 
  c.id,
  'Statistics & Data Analysis',
  'Analyze real-world data sets using statistical methods',
  CURRENT_DATE + INTERVAL '2 days',
  90,
  'active'
FROM public.classes c WHERE c.name = 'Advanced Math - Grade 11'
LIMIT 1;

-- Sample class schedule
INSERT INTO public.class_schedule (class_id, day_of_week, start_time, end_time, topic)
SELECT 
  c.id,
  1, -- Monday
  '09:00:00',
  '10:00:00',
  'Quadratic Equations'
FROM public.classes c WHERE c.name = 'Mathematics - Grade 10A'
LIMIT 1;

INSERT INTO public.class_schedule (class_id, day_of_week, start_time, end_time, topic)
SELECT 
  c.id,
  1, -- Monday
  '10:30:00',
  '11:30:00',
  'Functions & Graphs'
FROM public.classes c WHERE c.name = 'Mathematics - Grade 10B'
LIMIT 1;

INSERT INTO public.class_schedule (class_id, day_of_week, start_time, end_time, topic)
SELECT 
  c.id,
  1, -- Monday
  '14:00:00',
  '15:00:00',
  'Trigonometry'
FROM public.classes c WHERE c.name = 'Advanced Math - Grade 11'
LIMIT 1;

-- Sample alerts (replace teacher_id with actual UUID)
-- INSERT INTO public.alerts (teacher_id, class_id, alert_type, priority, title, message, action_url)
-- VALUES
--   ('TEACHER_UUID', 'CLASS_UUID', 'mastery_threshold', 'high', '5 students below mastery threshold in Algebra', 'Students need additional support in quadratic equations', '/teacher/dashboard?tab=mastery'),
--   ('TEACHER_UUID', 'CLASS_UUID', 'engagement_drop', 'medium', 'Engagement dropped in last session', '20% decrease compared to previous week average', '/teacher/dashboard?tab=engagement'),
--   ('TEACHER_UUID', 'CLASS_UUID', 'project_milestone', 'medium', 'PBL milestone due tomorrow (3 teams)', 'Review project submissions and provide feedback', '/teacher/dashboard?tab=projects');

-- Note: Run this after setting up authentication and getting real user IDs
